/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class dice_service_roll_DiceRoller */

#ifndef _Included_dice_service_roll_DiceRoller
#define _Included_dice_service_roll_DiceRoller
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     dice_service_roll_DiceRoller
 * Method:    getRandomDeviceInstance
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_dice_service_roll_DiceRoller_getRandomDeviceInstance
  (JNIEnv *, jclass);

/*
 * Class:     dice_service_roll_DiceRoller
 * Method:    performRolls
 * Signature: (J[Ldice/common/types/IDiceRollType;I)V
 */
JNIEXPORT void JNICALL Java_dice_service_roll_DiceRoller_performRolls
  (JNIEnv *, jobject, jlong, jobjectArray, jint);

#ifdef __cplusplus
}
#endif
#endif
